"""
config.py
"""

import json
from pathlib import Path


FPS: int = 120
TPS: int = 20

UNITS_PER_CHUNK: int = 16
PIXELS_PER_UNIT: int = 16

DISPLAY_WIDTH: int = 800
DISPLAY_HEIGHT: int = 600

GENERATOR_NOISE_AMPLITUDE: float = 64.0
GENERATOR_NOISE_FIDELITY: float = 1.0
GENERATOR_NOISE_LACUNARITY: float = 8.0
GENERATOR_NOISE_OCTAVES: float = 4.0
GENERATOR_NOISE_PERSISTENCE: float = 0.5
GENERATOR_NOISE_SCALE: float = 256.0
GENERATOR_OFFSET_AMPLITUDE: float = 0.0
GENERATOR_OFFSET_CURVATURE: float = 4.0
GENERATOR_OFFSET_LENGTH: float = 64.0
GENERATOR_FALLOFF_CURVATURE: float = 0.01

PLAYER_DEBUG_SPEED: float = 24.0
PLAYER_HORIZONTAL_SPEED: float = 64.0
PLAYER_JUMP_STRENGTH: float = 64.0

GRAVITATIONAL_CONSTANT: float = 9.8 * 2
